stage: prod

studySyncApp:
  ALBFargateServiceCPU: 256
  ALBFargateServiceMemoryLimitMib: 512
  ALBFargateServiceServiceCount: 1
  ecsInstanceType: "t3.micro"
  env:
    CONTAINER_PORT: "8080"
    NODE_ENV: "production"
  fargateTaskCPU: 256
  fargateTaskMemoryLimitMib: 512
  imageTag: "1.0.0"
